### ISSUE TITLE
An error when loading the provided checkpoint

### ISSUE THREAD

**Issue by Jize-W** [BorealisAI/code-gen-TAE#2]
Hello,

When I evaluate the provided checkpoint, an error occurs. There seems to be something wrong when loading the weights. How to fix that?

`python3 train.py --dataset_name django --save_dir pretrained_weights/django --copy_bt --no_encoder_update --monolingual_ratio 1.0 --early_stopping --just_evaluate --seed 2
`

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

min 3
max 98
std 14.170321655300544
mean 22.273910582908886
Effective batch size 8
model name django_model_combined_training=False_seed=2_trns_back=False_use_backtr=False_lmd=1_cp_bt=True_add_no=False_no_en_upd=True_ratio=1.0_ext_li=True_ext_cp_li=True_cp_att=True_EMA=T_rnd_enc=F_de_lr=7.5e-05_mmp=0.1_saug=F_dums=F_dumQ=F_rsr=F_fc=F_ccr=F.pth
copy dataset size 105983
train set size: 15903
dev set size 1000
test set size 1805
example of parallel data
[CLS] from threading import local into default name space. [SEP]
[CLS] from threading import local [SEP]
105983
example of monolingual data
[CLS] sort a nested list by two elements [SEP]
[CLS] sorted ( l, key = lambda x : ( - int ( x [ 1 ] ), x [ 0 ] ) ) [SEP]
Traceback (most recent call last):
  File "train.py", line 359, in <module>
    train(args)
  File "train.py", line 220, in train
    model.load_state_dict(torch.load(os.path.join(args.save_dir, model_name)))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by sajadn** [comment]
can you try [this](https://stackoverflow.com/a/67141340/5214998) solution and let me know if it solves your issue?

**Comment by Jize-W** [comment]
It works. Thanks a lot!
